name: 모의 자동매매 시스템

on:
  schedule:
    # 매일 한국 시간 오전 8시 30분 (UTC 23:30)에 실행
    - cron: '30 23 * * *'
  workflow_dispatch:
    # 수동 실행 옵션

jobs:
  auto-trading:
    runs-on: ubuntu-latest
    timeout-minutes: 180  # 최대 실행시간: 3시간
    
    env:
      MOCK_INITIAL_CAPITAL: "10000000"  # 모의 자본금 (1천만원)
      KR_MARKET_OPEN_TIME: "09:00"  # 한국 시장 시작 시간
      KR_MARKET_CLOSE_TIME: "15:30"  # 한국 시장 종료 시간
      USE_KAKAO: "true"  # 카카오톡 알림 활성화
      USE_GPT_ANALYSIS: "true"  # GPT 분석 활성화
      FORCE_MARKET_OPEN: "true"  # 테스트를 위해 시장 강제 오픈
      MAX_RUNTIME_MINUTES: "170"  # 실제 실행 시간 (자동 재시작 고려)

    steps:
      - name: 체크아웃 코드
        uses: actions/checkout@v4

      - name: Python 설정
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: 의존성 설치
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: 시스템 정보 출력
        run: |
          echo "현재 시간 (KST): `TZ='Asia/Seoul' date`"
          echo "현재 시간 (UTC): `date`"
          echo "Python 버전: `python --version`"
          echo "작업 디렉토리: `pwd`"
          ls -la

      - name: 모의 자동매매 실행 (자동 재시작 기능 포함)
        env:
          RESTART_COUNT: "10"  # 최대 재시작 횟수
        run: |
          for attempt in $(seq 1 $RESTART_COUNT); do
            echo "자동매매 실행 시도 #$attempt/$RESTART_COUNT"
            start_time=$(date +%s)
            
            # 타임스탬프 로그 파일명 생성
            timestamp=$(date +%Y%m%d_%H%M%S)
            log_file="mock_auto_trading_${timestamp}.log"
            
            # 실행
            python test_mock_auto_trading.py || true
            
            end_time=$(date +%s)
            duration=$((end_time - start_time))
            
            echo "실행 완료: $duration 초 동안 실행됨"
            
            # 실행 시간이 너무 짧으면(오류) 대기시간 증가
            if [ $duration -lt 60 ]; then
              echo "오류 감지: 실행이 너무 빨리 종료되었습니다. 30초 대기 후 재시작합니다."
              sleep 30
            else
              echo "정상 종료 또는 타임아웃: 5초 후 재시작합니다."
              sleep 5
            fi
          done
          
          echo "모든 재시작 시도가 완료되었습니다."

      - name: 로그 파일 업로드
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: trading-logs
          path: |
            mock_auto_trading*.log
            *.log