name: Market Analysis and Mock Trading

on:
  schedule:
    # 한국 시장 시간 (오전 9시, 오후 3시 30분)
    - cron: '0 0 * * 1-5'   # UTC 기준 월-금 00:00 (한국 시간 09:00)
    - cron: '30 6 * * 1-5'  # UTC 기준 월-금 06:30 (한국 시간 15:30)
    
    # 미국 시장 시간 (밤 10시 30분, 새벽 5시)
    - cron: '30 13 * * 1-5' # UTC 기준 월-금 13:30 (한국 시간 22:30)
    - cron: '0 20 * * 1-5'  # UTC 기준 월-금 20:00 (한국 시간 05:00)
  
  # 수동으로도 워크플로우 실행 가능하게 설정
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run market analysis and mock trading
      run: python test_mock_auto_trading.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
    
    - name: Upload log files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: market-analysis-logs
        path: |
          mock_auto_trading.log
          stock_analysis.log