name: Real Trading (Currently Disabled)

on:
  # 실제 매매는 현재 비활성화 상태입니다
  # schedule:
  #   # 한국 시장 시간 (오전 9시, 오후 3시 30분)
  #   - cron: '0 0 * * 1-5'   # UTC 기준 월-금 00:00 (한국 시간 09:00)
  #   - cron: '30 6 * * 1-5'  # UTC 기준 월-금 06:30 (한국 시간 15:30)
  #   
  #   # 미국 시장 시간 (밤 10시 30분, 새벽 5시)
  #   - cron: '30 13 * * 1-5' # UTC 기준 월-금 13:30 (한국 시간 22:30)
  #   - cron: '0 20 * * 1-5'  # UTC 기준 월-금 20:00 (한국 시간 05:00)
  
  # 수동으로만 실행 가능하게 설정 (실수로 실행되는 것 방지)
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run real trading
      run: python main.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
        KAKAO_ACCESS_TOKEN: ${{ secrets.KAKAO_ACCESS_TOKEN }}
        KAKAO_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KIS_APP_KEY: ${{ secrets.KIS_APP_KEY }}
        KIS_APP_SECRET: ${{ secrets.KIS_APP_SECRET }}
        KIS_ACCOUNT_NO: ${{ secrets.KIS_ACCOUNT_NO }}
        KIS_PERSONALSECKEY: ${{ secrets.KIS_PERSONALSECKEY }}
        # 현재는 모의 투자로 설정 (실제 매매로 전환 시 true로 변경)
        KIS_REAL_TRADING: "false"
    
    - name: Display log files
      run: |
        echo "=== Trading Log ==="
        if [ -f trading.log ]; then
          tail -n 50 trading.log
        fi
        echo "=== Stock Analysis Log ==="
        if [ -f stock_analysis.log ]; then
          tail -n 50 stock_analysis.log
        fi