name: Stock Recommendation Analysis

on:
  schedule:
    # 매일 아침 8시 30분(한국 시간 기준, UTC+9)에 실행 - 시장 개장 전
    - cron: '30 23 * * 0-4'  # UTC 기준 월-금 23:30 (한국 시간으로 아침 8:30)
  
  # 수동으로도 워크플로우 실행 가능하게 설정
  workflow_dispatch:

jobs:
  analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Run stock recommendation script
      run: python test_stock_recommendation.py
      env:
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        KAKAO_REST_API_KEY: ${{ secrets.KAKAO_REST_API_KEY }}
        KAKAO_REFRESH_TOKEN: ${{ secrets.KAKAO_REFRESH_TOKEN }}
    
    - name: Upload log files as artifacts
      uses: actions/upload-artifact@v2
      with:
        name: stock-recommendation-logs
        path: |
          stock_recommendation_test.log
          gpt_stock_analysis.log